config/routes.rb
Rails.application.routes.draw do
  resources :blocks, only: [:index] do
    get ':blockhash', to: 'blocks#show', on: :collection, as: :show
  end
  resources :transactions, only: [:index, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/block.rb
class Block < ApplicationRecord
  belongs_to :previousblock, class_name: "Block", optional: true
  has_many :txs

  def next_block
    Block.find_by(previousblock: self)
  end
end

app/models/blockchain.rb
class Blockchain < ApplicationRecord
end

app/models/blockchain_task.rb
class BlockchainTask
  include Delayed::RecurringJob
  run_every 1.minutes
  queue :default
  def perform
    BlockchainJob.perform_later
  end
end

app/models/tx.rb
class Tx < ApplicationRecord
  belongs_to :block
  self.table_name = "txs"
end

app/models/tx_in.rb
class TxIn < ApplicationRecord
  belongs_to :tx
end

app/models/tx_out.rb
class TxOut < ApplicationRecord
  belongs_to :tx
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
end

app/controllers/blocks_controller.rb
class BlocksController < ApplicationController
  def index
    @blocks = Block.order(height: :desc).page(params[:page]).per(20)
  end

  def show
    @block = Block.find_by(blockhash: params[:blockhash])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blocks_helper.rb
module BlocksHelper
  def format_date(utc)
    Time.zone.at(utc).strftime("%F %T")
  end
end

app/views/blocks/index.html.slim
.container
  table.striped
    thead
      tr
        th
          | Height
        th
          | Hash
        th
          | Block time (UTC)
        th
          | Size (bytes)
    tbody
      - @blocks.each do |block|
        tr
          td = block.height
          td = link_to block.blockhash, show_blocks_path(block.blockhash)
          td = format_date(block.time)
          td = block.size
  = paginate @blocks

app/views/blocks/show.html.slim
h2 = render "shared/breadcrumb", contents: [{ label: "Blocks", path: blocks_path }, { label: @block.height }]

table
  tbody
    tr
      td
        | Hash
      td
        = @block.blockhash
    tr
      td
        | Previous Block Hash
      td
        - if @block.previousblockhash
          = link_to @block.previousblockhash, show_blocks_path(@block.previousblockhash)
    tr
      td
        | Next Block Hash
      td
        - if @block.next_block
          = link_to @block.next_block.blockhash, show_blocks_path(@block.next_block.blockhash)
    tr
      td
        | Confirmations
      td
        
    tr
      td
        | Block time (UTC)
      td
        = format_date(@block.time)
    tr
      td
        | Height
      td
        = @block.height
    tr
      td
        | Number of Transactions
      td
        = @block.txs.count
    tr
      td
        | Difficulty
      td
        = @block.difficulty
    tr
      td
        | Merkle root
      td
        = @block.merkleroot
    tr
      td
        | Version
      td
        = @block.versionhex
    tr
      td
        | Bits
      td
        = @block.bits
    tr
      td
        | Size (bytes)
      td
        = @block.size
    tr
      td
        | Weight
      td
        = @block.weight
    tr
      td
        | Nonce
      td
        = @block.nonce
    tr
      td
        | Transaction Volume
      td
    tr
      td
        | Block Reward
      td
    tr
      td
        | Fee Reward
      td

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Btc2ar
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  body
    header.navbar-fixed 
      nav class="#{@color}"
        a#sidenav href="#" data-target="slide-out" class="button-collapse sidenav-trigger show-on-large" data-turbolinks="false"
          i class="material-icons right" apps 
        Bitcoin Block Explorer
    main
      .container
        = yield

app/views/shared/_breadcrumb.html.slim
.valign-wrapper
  - contents.each do |content|
    = link_to content[:label], (content[:path] || '#'), class: "breadcrumb"